name: Terraform Destroy

on: workflow_dispatch

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        name: Clone repository

      # terraform_wrapper: false -> required to get the detailed exit code from terraform plan command!
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false
        name: Install Terraform

      - uses: azure/login@v3
        with:
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
        name: Log in to Azure

      - run: |
          terraform init
          terraform destroy -auto-approve
        name: Destroy all resources