name: Terraform Drift Detection

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        name: Clone repository

      - uses: hashicorp/setup-terraform@v4
        name: Install Terraform

      - uses: azure/login@v3
        with:
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
        name: Log in to Azure

      - run: |
          set +e
          terraform init
          terraform plan -out tfplan -detailed-exitcode
          plan_exit_code=$?
          echo "exit_code=$plan_exit_code" >> $GITHUB_OUTPUT
          echo "Exit code: $plan_exit_code"
        id: tfplan
        name: Detect drift

      - run: |
          echo "Exit code output: ${{ steps.tfplan.outputs.exit_code }}"
        name: Show exit code

      - run: |
          terraform show -json tfplan > tfplan.tfgraph

          gh issue create -t ":rotating_light: Infrastructure drift detected!" -b "Infrastructure drift was detected in workflow run https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        if: steps.tfplan.outputs.exit_code == '2'
        name: Create Terraform graph and drift issue
        env:
          GH_TOKEN: ${{ github.token }}
      
      - uses: actions/upload-artifact@v7
        if: steps.tfplan.outputs.exit_code == '2'
        with:
          path: tfplan*
          name: plan
        name: Save plan for demo